# Generated by Django 2.1.1 on 2018-09-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=400)),
                ('comment_date', models.DateTimeField(verbose_name='date commented')),
                ('sender_ip', models.CharField(max_length=20)),
            ],
        ),
    ]
